import { Button } from "@/components/ui/button";
import { Download, Share2, Star, Calendar, MapPin, Clock } from "lucide-react";
import KundaliChart from "./KundaliChart";
import type { KundaliData, KundaliFormData } from "@/types/kundali";

interface ResultSectionProps {
  kundaliData: KundaliData;
  formData: KundaliFormData;
  paymentId: string | null;
}

export default function ResultSection({ kundaliData, formData, paymentId }: ResultSectionProps) {
  const downloadPDF = async () => {
    try {
      // Check if jsPDF is available
      if (!(window as any).jsPDF) {
        // Load jsPDF dynamically
        const script = document.createElement('script');
        script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
        script.onload = () => downloadPDF();
        document.head.appendChild(script);
        return;
      }

      const { jsPDF } = (window as any).jspdf;
      const pdf = new jsPDF();
      
      // Add title
      pdf.setFontSize(20);
      pdf.setTextColor(108, 92, 231);
      pdf.text('Vedic Kundali Report', 20, 30);
      
      // Add personal details
      pdf.setFontSize(12);
      pdf.setTextColor(0, 0, 0);
      
      let y = 50;
      pdf.text(`Name: ${formData.fullName}`, 20, y);
      y += 10;
      pdf.text(`Date of Birth: ${new Date(formData.dateOfBirth).toLocaleDateString('en-GB')}`, 20, y);
      y += 10;
      pdf.text(`Time of Birth: ${formData.timeOfBirth || '12:00 (assumed)'}`, 20, y);
      y += 10;
      pdf.text(`Place of Birth: ${formData.placeOfBirth}`, 20, y);
      y += 20;
      
      // Add basic analysis
      pdf.setFontSize(14);
      pdf.setTextColor(0, 206, 201);
      pdf.text('Basic Analysis', 20, y);
      y += 10;
      
      pdf.setFontSize(10);
      pdf.setTextColor(0, 0, 0);
      pdf.text(`Zodiac Sign: ${kundaliData.basic_analysis.zodiac_sign}`, 20, y);
      y += 8;
      pdf.text(`Moon Sign: ${kundaliData.basic_analysis.moon_sign}`, 20, y);
      y += 8;
      pdf.text(`Ascendant: ${kundaliData.basic_analysis.ascendant}`, 20, y);
      y += 8;
      pdf.text(`Birth Star: ${kundaliData.basic_analysis.birth_star}`, 20, y);
      y += 15;
      
      // Add planetary positions
      pdf.setFontSize(14);
      pdf.setTextColor(0, 206, 201);
      pdf.text('Planetary Positions', 20, y);
      y += 10;
      
      pdf.setFontSize(9);
      pdf.setTextColor(0, 0, 0);
      kundaliData.planetary_positions.forEach(planet => {
        pdf.text(`${planet.name}: ${planet.sign} (${planet.degree}°)`, 20, y);
        y += 6;
        if (y > 270) { // Start new page if needed
          pdf.addPage();
          y = 20;
        }
      });
      
      // Footer
      pdf.setFontSize(8);
      pdf.setTextColor(128, 128, 128);
      pdf.text('Generated by Witchcard Astrology - witchcard.shop', 20, 285);
      if (paymentId) {
        pdf.text(`Payment ID: ${paymentId}`, 20, 290);
      }
      
      // Save PDF
      pdf.save(`kundali-${formData.fullName.replace(/\s+/g, '-')}.pdf`);
    } catch (error) {
      console.error('PDF generation error:', error);
      alert('Failed to generate PDF. Please try again.');
    }
  };

  const shareWhatsApp = () => {
    const message = `✨ My Vedic Kundali Report ✨

🌟 Personal Details:
Name: ${formData.fullName}
DOB: ${new Date(formData.dateOfBirth).toLocaleDateString('en-GB')}
Place: ${formData.placeOfBirth}

🔮 Basic Analysis:
• Zodiac Sign: ${kundaliData.basic_analysis.zodiac_sign}
• Moon Sign: ${kundaliData.basic_analysis.moon_sign}
• Ascendant: ${kundaliData.basic_analysis.ascendant}
• Birth Star: ${kundaliData.basic_analysis.birth_star}

🪐 Key Planetary Positions:
${kundaliData.planetary_positions.slice(0, 5).map(p => `• ${p.name}: ${p.sign} (${p.degree}°)`).join('\n')}

Generated from: ${window.location.origin}/kundali`;

    const encodedMessage = encodeURIComponent(message);
    const whatsappUrl = `https://wa.me/?text=${encodedMessage}`;
    
    window.open(whatsappUrl, '_blank');
  };

  return (
    <div className="glassmorphism rounded-3xl p-8">
      <h3 className="font-orbitron text-3xl text-center gradient-text mb-8">
        Your Cosmic Blueprint
      </h3>
      
      {/* Personal Details Summary */}
      <div className="glassmorphism rounded-2xl p-6 mb-8">
        <h4 className="font-orbitron text-xl text-ethereal-500 mb-4 flex items-center gap-2">
          <Star className="h-5 w-5" />
          Personal Details
        </h4>
        <div className="grid md:grid-cols-2 gap-4 text-sm">
          <div className="flex items-center justify-between">
            <span className="text-white/70 flex items-center gap-2">
              <Star className="h-4 w-4" />
              Name:
            </span>
            <span className="text-white font-semibold">{formData.fullName}</span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-white/70 flex items-center gap-2">
              <Calendar className="h-4 w-4" />
              Date of Birth:
            </span>
            <span className="text-white font-semibold">
              {new Date(formData.dateOfBirth).toLocaleDateString('en-GB')}
            </span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-white/70 flex items-center gap-2">
              <Clock className="h-4 w-4" />
              Time of Birth:
            </span>
            <span className="text-white font-semibold">
              {formData.timeOfBirth || '12:00 (assumed)'}
            </span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-white/70 flex items-center gap-2">
              <MapPin className="h-4 w-4" />
              Place of Birth:
            </span>
            <span className="text-white font-semibold truncate max-w-48" title={formData.placeOfBirth}>
              {formData.placeOfBirth}
            </span>
          </div>
        </div>
      </div>

      {/* Chart Container */}
      <div className="grid lg:grid-cols-2 gap-8 mb-8">
        {/* Kundali Chart */}
        <KundaliChart 
          houses={kundaliData.houses} 
          planets={kundaliData.planetary_positions} 
        />
        
        {/* Planetary Positions */}
        <div className="glassmorphism rounded-2xl p-6">
          <h4 className="font-orbitron text-xl text-ethereal-500 mb-4">Planetary Positions</h4>
          <div className="space-y-3 text-sm max-h-64 overflow-y-auto">
            {kundaliData.planetary_positions.map((planet) => (
              <div key={planet.id} className="flex justify-between border-b border-white/10 pb-2">
                <span className="text-white/70">{planet.name}:</span>
                <span className="text-white font-semibold">
                  {planet.sign} ({planet.degree}°)
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Basic Analysis */}
      <div className="glassmorphism rounded-2xl p-6 mb-8">
        <h4 className="font-orbitron text-xl text-ethereal-500 mb-4">Basic Analysis</h4>
        <div className="grid md:grid-cols-2 gap-4 text-sm">
          <div className="flex justify-between border-b border-white/10 pb-2">
            <span className="text-white/70">Zodiac Sign:</span>
            <span className="text-white font-semibold">{kundaliData.basic_analysis.zodiac_sign}</span>
          </div>
          <div className="flex justify-between border-b border-white/10 pb-2">
            <span className="text-white/70">Moon Sign:</span>
            <span className="text-white font-semibold">{kundaliData.basic_analysis.moon_sign}</span>
          </div>
          <div className="flex justify-between border-b border-white/10 pb-2">
            <span className="text-white/70">Ascendant:</span>
            <span className="text-white font-semibold">{kundaliData.basic_analysis.ascendant}</span>
          </div>
          <div className="flex justify-between border-b border-white/10 pb-2">
            <span className="text-white/70">Birth Star:</span>
            <span className="text-white font-semibold">{kundaliData.basic_analysis.birth_star}</span>
          </div>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex flex-wrap gap-4 justify-center">
        <Button 
          onClick={downloadPDF}
          className="mystic-btn px-6 py-3 rounded-xl text-white font-semibold flex items-center gap-2 transition-all duration-300"
        >
          <Download className="h-4 w-4" />
          Download PDF
        </Button>
        <Button 
          onClick={shareWhatsApp}
          className="bg-green-600 hover:bg-green-700 px-6 py-3 rounded-xl text-white font-semibold flex items-center gap-2 transition-all duration-300"
        >
          <Share2 className="h-4 w-4" />
          Share on WhatsApp
        </Button>
      </div>

      {paymentId && (
        <p className="text-white/60 text-xs text-center mt-6">
          Payment ID: {paymentId} | Generated by Witchcard Astrology
        </p>
      )}
    </div>
  );
}
